name:                fork-shop
version:             0.1.0.0
github:              "Fayarendill/fork_shop"
license:             BSD3
author:              "Fayarendill"
maintainer:          "voinov.forever@gmail.com"
copyright:           "2019 Fayarendill"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Fayarendill/fork_shop#readme>

dependencies:
- base >= 4.7 && < 5
- haxl >= 2.1.2.0
- hashable >= 1.2.7.0
- containers >= 0.6
- HDBC-mysql >= 0.7.1.0
- regex-compat >= 0.95.2.0
- chronos >= 1.0.9
- transformers >= 0.4
- haskelldb >= 2.2.4
- scotty >= 0.6
- wai
- warp
- http-types
- resourcet
- text
- bytestring
- blaze-html
- persistent >=2
- persistent-template >=2
- monad-logger >= 0.3
- heroku
- wai-middleware-static
- wai-extra
- time
- mysql-simple >= 0.4.5
- persistent-mysql >= 2.9.0

library:
  source-dirs: src

executables:
  fork-shop-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fork-shop

tests:
  fork-shop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fork-shop
